#cloud-config

packages:

- ansible
- git
- python-pip

runcmd:

- yum update -y
- pip install --upgrade pip
- pip install redis
- mkdir /var/log/ansible/ansible.log
- echo -e "[localhost]\n127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
#:- ssh-keyscan github.com >> /etc/ssh/ssh_known_hosts
- ansible-pull -d /etc/ansible/ansible-pull -U https://github.com/shterrel/ansible-pull.git ansible-examples/wordpress-nginx_rhel7/site.yml
