---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  connection: local
  #remote_user: root
  gather_facts: false
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
